name: Pull Request
run-name: ${{ github.workflow }} - ${{ github.ref_name }}

on:
  pull_request:
    types: [opened, synchronize, reopened, assigned, review_requested]
  workflow_dispatch:

jobs:
  pullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print PR Information
        run: |
          echo "🔍 Pull Request Details"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "PR Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "PR Head Branch: ${{ github.event.pull_request.head.ref }}"
          echo "PR State: ${{ github.event.pull_request.state }}"
          date

      - name: List changed files
        continue-on-error: true
        run: |
          echo "📝 Changed files in this PR:"
          git diff --name-only ${{ github.event.pull_request.base.sha }}..HEAD

      - name: Checkout code
        uses: actions/checkout@v6