name: Push Workflow
run-name: ${{ github.actor }} is testing out GitHub Action

on:
  push:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Print ENVS
        run: |
         date
         pwd
         whoami

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"